-- Lua
vim.keymap.set('n', '<leader>xx', function()
  require('trouble').toggle('diagnostics')
end, { desc = 'problems' })
vim.keymap.set('n', '<leader>xq', function()
  require('trouble').toggle('quickfix')
end, { desc = 'quickfix' })
vim.keymap.set('n', '<leader>xl', function()
  require('trouble').toggle('loclist')
end, { desc = 'loclist' })
vim.keymap.set('n', 'gR', function()
  require('trouble').toggle('lsp_references')
end, { desc = 'lsp references' })
